#файл для компоновки контейнеров, используется для старта докера
version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 50004:4000
    # volumes:
    #   - .:/frontend
    
