#файл для компоновки контейнеров, используется для старта докера
version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/frontend
