name: Master deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: curl testing
        run: curl -v telnet://94.26.230.80:22
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: echo test